"""empty message

Revision ID: 1729f5a1a906
Revises: 4fa8ba53f09b
Create Date: 2024-01-22 09:39:43.571184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1729f5a1a906'
down_revision = '4fa8ba53f09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_produc_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint('product_produc_name_key', ['produc_name'])

    # ### end Alembic commands ###
