"""empty message

Revision ID: 87dde3501dbe
Revises: 52c3e2f2daac
Create Date: 2024-01-22 10:15:42.626442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87dde3501dbe'
down_revision = '52c3e2f2daac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produc_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('product_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    # ### end Alembic commands ###
