"""empty message

Revision ID: c6c9d1ce1147
Revises: 17b2da6f9802
Create Date: 2024-02-20 18:13:49.456866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c9d1ce1147'
down_revision = '17b2da6f9802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_be', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provincia', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_be', schema=None) as batch_op:
        batch_op.drop_column('provincia')

    # ### end Alembic commands ###
